language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t chervinvananaz/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true chervinvananaz/react-test yarn test

after_success:
  - docker build -t chervinvananaz/multi-client ./client
  - docker build -t chervinvananaz/multi-nginx ./nginx
  - docker build -t chervinvananaz/multi-server ./server
  - docker build -t chervinvananaz/multi-worker ./worker
  # Login first to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push them to Dockerhub
  - docker push chervinvananaz/multi-client
  - docker push chervinvananaz/multi-nginx
  - docker push chervinvananaz/multi-server
  - docker push chervinvananaz/multi-worker
