version: "3"
services:
  client:
    image: "chervinvananaz/multi-client"
    hostname: client
  server:
    image: "chervinvananaz/multi-server"
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "chervinvananaz/multi-worker"
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "chervinvananaz/multi-nginx"
    hostname: nginx
    ports:
      - "80:80"
# {
#   "AWSEBDockerrunVersion": 2,
#   "containerDefinitions": [
#     {
#       "name": "client",
#       "image": "chervinvananaz/multi-client",
#       "hostname": "client",
#       "essential": false
#     },
#     {
#       "name": "server",
#       "image": "chervinvananaz/multi-server",
#       "hostname": "api",
#       "essential": false
#     },
#     {
#       "name": "worker",
#       "image": "chervinvananaz/multi-worker",
#       "hostname": "worker",
#       "essential": false
#     },
#     {
#       "name": "nginx",
#       "image": "chervinvananaz/multi-nginx",
#       "hostname": "nginx",
#       "essential": true,
#       "portMappings": [
#         {
#           "hostPort": 80,
#           "containerPort": 80
#         }
#       ],
#       "links": ["client", "server"]
#     }
#   ]
# }